management:
  port: 9876
  security:
    enabled: false

logging:
  level:
    ROOT: INFO
#    org.springframework.security: INFO
    
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

spring:
  rabbitmq:
    host: localhost
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
---
spring.profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq
  zipkin:
      base-url: http://zipkin:9411
